### ISSUE TITLE
 InvalidArgumentException: Middleware not found exception when creating client

### ISSUE THREAD

**Issue by cam8001** [akamai/AkamaiOPEN-edgegrid-php-client#19]
I am building an [integration module for Drupal 8](https://github.com/d8-contrib-modules/akamai). Instead of using an `.edgrec` file, I am managing configuration using Drupal's [configuration API](https://www.drupal.org/node/1667894).

When I instantiate the client, I get this exception:

`InvalidArgumentException: Middleware not found: history in /Users/cameron.tod/Sites/drupal/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 220`

Here's the code I use to create the client: https://github.com/cam8001/akamai/blob/16/integrate-akamai-library/src/AkamaiClient.php#L44

And here's the line that trips the Exception:

https://github.com/akamai-open/AkamaiOPEN-edgegrid-php/blob/master/src/Client.php#L445

I dont _think_ I'm doing anything wrong. Is this a bug? Is it likely to cause issues down the line?

**Comment by dshafik** [comment]
Hi @cam8001,

This is great to see! I'd love to see better integration with Drupal 8 and will do what I can help you with that! :)

This issue seems very odd, as you can see on [Line 446](https://github.com/akamai-open/AkamaiOPEN-edgegrid-php/blob/master/src/Client.php#L446), there is a `catch (\InvalidArgumentException)` which should catch this exact exception. 

What's happening is that the authentication handler needs to be added to the handler stack _before_ the history handler **if** it has been added. Unfortunately, Guzzle provides no way to check if something is in the stack, so we attempt to add it before (Line 445), and if that fails this exception is thrown — we then just add it to the end of the stack (Line 448).

So yes, the exception is _expected_ in some scenarios, and should be handled… 

If I create a test case that replicates the pertinent bits of your code, as below, it passes just fine:

``` php
// Test class
class ClientExtended extends Client {
    public static function create($client_token, $client_secret, $access_token)
    {
        $config = ['timeout' => 5];
        $instance = new static($config);
        $instance->setAuth($client_token, $client_secret, $access_token);

        return $instance;
    }
}

// test case
public function testIssue19ExtendStaticInstantiate()
{
    $access_token = "akab-access-token-xxx-xxxxxxxxxxxxxxxx";
    $client_token = "akab-client-token-xxx-xxxxxxxxxxxxxxxx";
    $client_secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=";

    $instance = ClientExtended::create($client_token, $client_secret, $access_token);
    $this->assertInstanceOf(ClientExtended::class, $instance);
}
```

Can you confirm that you are using 0.4.2? Are you installing via Composer, or using the PHAR?

**Comment by cam8001** [comment]
Thanks for the excellent response!

As it turns out I had an over-enthusiastic XDebug config that was notified me about every Exception whether it was caught or not (`xdebug.show_exception_trace=1`). 

Great to open the lines of communication though - I'm sure I'll call on you again ;).
